### ISSUE TITLE
Aggiungere utilizzo delle frecce per navigare il risultato della ricerca

### ISSUE THREAD

**Issue by lucapiccinelli** [Studiofarma/Infolab#126]

**Comment by paolo-venturi** [comment]
Se il focus è posizionato sulla barra di ricerca dovrebbe essere possibile navigare nell'elenco dei contatti usando le frecce della tastiera

**Comment by paolo-venturi** [comment]
La selezione della conversazione viene poi eseguito dopo la pressione del tasto invio
