### ISSUE TITLE
Cambio editor

### ISSUE THREAD

**Issue by paolo-venturi** [Studiofarma/Infolab#160]
Scegliere il miglior editor [WYSIWYG ](https://it.wikipedia.org/wiki/WYSIWYG) utilizzare per la chat:
- ricercare i pacchetti migliori
- stilare una lista di pro e contro dei vari pacchetti
- valutare la facilità di inserimento nell'applicazione

**Comment by MalgarottiMirko** [comment]
https://quilljs.com/
	Pro:
		* Interfaccia semplice
		* Facile da configurare
		* Facile da integrare
		* Personalizzabile

https://trix-editor.org/
	Pro:
		* Interfaccia semplice
		* Facile da integrare
	Contro:
		* Poca personalizzazione

https://yabwe.github.io/medium-editor/
	Pro:
		* Interfaccia popup
		* Facile da utilizzare
		* Facile da integrare
	Contro:
		* Poca personalizzazione
		* Non lascia pieno controllo del testo (Nel playground se si seleziona una parte di testo e si imposta h2 o h3 lo applica a tutto il blocco di testo)
https://prosemirror.net/
	Pro:
		* Interfaccia semplice
	        * Facile da integrare
		* Facile da utilizzare
	Contro:
		* Pochi markdown
		* Poca personalizzazione
