### ISSUE TITLE
Refactoring componenti per lista messaggi

### ISSUE THREAD

**Issue by Guidetti-Daniele** [Studiofarma/Infolab#171]
Pensavo che dal componente potrebbe essere possibile passare i dati del messaggio come attributi. (vedere  immagine per situazione attuale del main)

![Image](https://github.com/Studiofarma/Infolab/assets/104075123/9a96f646-57cb-4581-8b8b-f782cdeb4c68)

**Comment by paolo-venturi** [comment]
Rifattorizzare il codice estraendo vari componenti:
- elenco messaggi
- menu messaggio
- contenuto messaggio
- etc...

Rivedere anche cartella e nomi dei componenti già esistenti riguardanti i messaggi
