### ISSUE TITLE
Aggiungere test che controlla che i messaggi siano stati effettivamente renderizzati

### ISSUE THREAD

**Issue by McGyv246** [Studiofarma/Infolab#215]
Non so se è fattibile, ma farebbe comodo vedere se i messaggi vengono renderizzati oltre che inviati (questo perché è capitato che i test passassero tutti e in verità i messaggi venivano mostrati solo se si ricaricava la pagina)

**Comment by paolo-venturi** [comment]
Mi aspetto lo si inserisca con la storia https://github.com/Studiofarma/Infolab/issues/186
