### ISSUE TITLE
Bug eliminazione messaggio

### ISSUE THREAD

**Issue by McGyv246** [Studiofarma/Infolab#235]
Quando un messaggio viene eliminato la chat viene scrollata fino in fondo.
Potrebbe essere comodo che dopo l'eliminazione e il re-render la chat rimanga dove era prima.

**Comment by paolo-venturi** [comment]
Al momento lasciamo così, quando ci sarà l'API di cancellazione gestiremo lo scroll e il segnalino di "messaggio eliminato"
