### ISSUE TITLE
Session storage per info utente

### ISSUE THREAD

**Issue by paolo-venturi** [Studiofarma/Infolab#262]
Memorizzare e mantenere aggiornate le informazioni relative all'utente loggato nel session storage.
Rimuovere le informazioni duplicate dal coockie nel quale vanno mantenute solo le informazioni utili al login e alle ultime chat.

**Comment by McGyv246** [comment]
Nella pr già mergiata sull'user service c'è già il salvataggio nel session storage dell'utente loggato. Inoltre attualmente l'unica info duplicata nel cookie è lo username, che però attualmente serve per il login.

Se non pensavi di modificare anche altre cose io chiuderei questo issue.
