### ISSUE TITLE
Utilizzare username come chiave esterna in tutte le JOIN

### ISSUE THREAD

**Issue by lucapiccinelli** [Studiofarma/Infolab#292]
- Modificare il liquibase utilizzando username come chiave esterna al posti user id. Non facciamo un nuovo changeset, ma rompiamo pure il vecchio db
 - Modificare tutte le JOIN in in cui viene utilizzato lo user id, sostituendolo con lo username
 - Ottimizzare tutte le query rimuovendo le join non più necessarie

**Comment by McGyv246** [comment]
Probabilmente sarebbe comodo fare lo stesso col roomname. Anche se il beneficio sarebbe minore rispetto a quello che si otterrà con lo username.
