### ISSUE TITLE
All'arrivo di un nuovo messaggio in una conversazione non aperta, non compare il numero di messaggi non letti

### ISSUE THREAD

**Issue by lucapiccinelli** [Studiofarma/Infolab#298]
![Image](https://github.com/Studiofarma/Infolab/assets/4964865/32b51bf2-fbda-4c0a-af9c-b88d067f5391)

**Comment by Guidetti-Daniele** [comment]
Si dovrebbe risolvere con la PR #296, appena sarà mergiata.
