### ISSUE TITLE
Svuotamento della barra dell'input al cambio di conversazione

### ISSUE THREAD

**Issue by Guidetti-Daniele** [Studiofarma/Infolab#299]
Poniamo che stia scrivendo un messaggio in una chat, se decido di cambiare conversazione senza inviare o cancellare il messaggio, mi rimane il contenuto dello stesso nella barra dell'input. Proporrei che al cambio di una conversazione, la barra dell'input venga svuotata.
Si potrebbe poi consentire che se si ritorna sulla chat dove si stava scrivendo il messaggio, la bozza rimanga salvata nella barra dell'input (come succede in What's App).

**Comment by lucapiccinelli** [comment]
Rimuovere il contenuto della barra di input al cambio di conversazione e ripristinare al rientro. 
Il contenuto va salvato e ripristinato anche alla chiusura del browser. Quando rientro sullo stesso client, mi aspetto di ritrovare la barra dell'input popolata con il testo che avevo iniziato.

Salverei il contenuto dell'input a seguito di ogni pressione dei tasti della tastiera. Utilizziamo il local storage.

Niente salvataggi a backend per ora. Va bene che su client differenti il contenuto non venga ripristinato
