### ISSUE TITLE
Bug con il numero di messaggi non letti

### ISSUE THREAD

**Issue by McGyv246** [Studiofarma/Infolab#312]
Quando scrivo in una chat seleziono un'altra chat e ricarico la pagina avrò dei  messaggi non letti (quelli scritti da me).

**Comment by Guidetti-Daniele** [comment]
Il  bug inoltre si estende anche nella forward list: se scrivo un messaggio in una chat e dopo vado in un'altra per inoltrare qualcosa, all'apertura della forward-list mi viene segnato il messaggio non letto. 



![Image](https://github.com/Studiofarma/Infolab/assets/104075123/16216854-499f-48d9-a1ad-c906ccb3d7f5)

**Comment by lucapiccinelli** [comment]
Rimuoviamo dalla get dei messaggi la scrittura della data di ultima lettura
