### ISSUE TITLE
Forward list non annulla la selezione

### ISSUE THREAD

**Issue by McGyv246** [Studiofarma/Infolab#320]
Quando si selezionano degli utenti nella forward list e poi si preme esc oppure si clicca al di fuori di essa (causandone la chiusura) alla nuova apertura gli utenti precedentemente selezionati saranno ancora selezionati.
Non so se è un comportamento voluto o un bug, nel dubbio l'ho segnalato.

**Comment by lucapiccinelli** [comment]
A me non sembra male. Io lo lascerei così
