### ISSUE TITLE
Modificare il nome utente anche nella label in alto a destra

### ISSUE THREAD

**Issue by lucapiccinelli** [Studiofarma/Infolab#329]
Quando viene modificato il nome utente, riportare la modifica anche nella label delle chat. Vedi screenshot. Non è richiesta la divulgazione della modifica tramite websocket.

Nella modale di modifica profilo, nascondiamo il bottone per il caricamento di una immagine di profilo. Lo rimostreremo quando sarà implementata anche a backend

![Image](https://github.com/Studiofarma/Infolab/assets/4964865/75f5bd2c-11fc-4f2c-8a2a-c7a7346c3ab3)

**Comment by McGyv246** [comment]
Paolo ci aveva detto di non cambiare il nome finché non sarebbe arrivato dal backend per evitare di implementare logica che poi sarebbe stata scartata.
