### ISSUE TITLE
Comunicazione su Web Socket per aggiornamento stato utente

### ISSUE THREAD

**Issue by paolo-venturi** [Studiofarma/Infolab#36]

**Comment by lucapiccinelli** [comment]
A seguito del login di un utente, il frontend deve mandare un messaggio a sul canale websocket d'entrata `chat.register`. Il messaggio di login deve poi essere divulgato a tutti gli altri client tramite websocket.

**Comment by McGyv246** [comment]
- Prima bisogna aggiungere la colonna alla tabella degli utenti e far sì che venga presa nell'api degli utenti
