### ISSUE TITLE
Gestione della chiusura delle connessioni (dopo 17 minuti)

### ISSUE THREAD

**Issue by lucapiccinelli** [Studiofarma/Infolab#53]
https://stackoverflow.com/questions/50587573/spring-websocket-is-automatically-closed-after-30-minutes-timeout

![Image](https://github.com/Studiofarma/Infolab/assets/4964865/30a1cbd4-0c47-4a25-b5f4-02d10a615565)

La websocket viene chiusa dopo 17 minuti. Sembrerebbe non essere una chisura del Server (come suggerito nel link sopra) bensì del client. Lo si può intuire dal fatto che il server continua a mandare le `h` dell'heartbeat di Stomp, rinnovando così la sessione.

Probabilmente, per risolvere bisogna usare una di queste due soluzioni:
 - riuscire a far mandare i ping (quelli del protocollo websocket, che sono diversi dagli heartbet stomp) dal server spring (similmente a quanto fatto nel devicehub server)
 - stare in ascolto lato client sulla chiusura della websocket e mettere una riconnessione (posticipandola di un secondo, per distinguere da disconnessioni dovute a chiusure della tab o del browser)

**Comment by lucapiccinelli** [comment]
Altra documentazione utile https://docs.spring.io/spring-framework/reference/web/websocket/server.html#websocket-server-runtime-configuration

**Comment by lucapiccinelli** [comment]
Forse però non è il client. Con queste istruzioni, si riesce ad accorciare la chiusura a 20 secondi

```Java
@Configuration
public class WebSocketConfig {

	@Bean
        public ServletServerContainerFactoryBean createWebSocketContainer() {
            ServletServerContainerFactoryBean container = new ServletServerContainerFactoryBean();
            log.info("timeout: %s".formatted(container.getMaxSessionIdleTimeout()));
            container.setMaxSessionIdleTimeout(20000L);
            return container;
        }

}
```

**Comment by lucapiccinelli** [comment]
Per pingare lato server, non avendo trovato una configurazione di spring, una possibile implemetazione parte da questo esempio

```Java
   @Bean
    public WebSocketHandler webSocketHandler(WebSocketHandler handler){
        return new WebSocketHandler() {
            @Override
            public void afterConnectionEstablished(WebSocketSession session) throws Exception {
                handler.afterConnectionEstablished(session);
            }

            @Override
            public void handleMessage(WebSocketSession session, WebSocketMessage<?> message) throws Exception {
                handler.handleMessage(session, message);
                session.sendMessage(new PingMessage());
            }

            @Override
            public void handleTransportError(WebSocketSession session, Throwable exception) throws Exception {
                handler.handleTransportError(session, exception);
            }

            @Override
            public void afterConnectionClosed(WebSocketSession session, CloseStatus closeStatus) throws Exception {
                handler.afterConnectionClosed(session, closeStatus);
            }

            @Override
            public boolean supportsPartialMessages() {
                return false;
            }
        };
```

nel metodo `afterConnectionEstablished` e `afterConnectionClosed` manteniamo una mappa delle sessioni aperte. Dopichè scheduliamo un controllore che itera le sessioni e manda messaggi di ping a tutte

**Comment by McGyv246** [comment]
Bisogna creare un'api internal che manda il ping.
Nell'esempio sopra bisogna aggiungere una mappa che funzioni in parallel che contiene tutte le sessions. Ci va un metodo che faccia il ping a ogni sessione.

Nota che il handleMessage va lasciato di default.
Nota anche che il non basterà una classe anonima e che servirà mettere il bean come primary.

**Comment by McGyv246** [comment]
Ho riscontrato vari problemi.
Il primo è che non ho trovato modo di far chiudere manualmente la connessione a tomcat nel modo in cui avviene dopo 30 min.
Il metodo presentato [sopra](https://github.com/Studiofarma/Infolab/issues/53#issuecomment-1690093970) non è la stessa cosa perché se si prova ad aumentare il timeout a 26 secondi, che è 1 secondo di più dell'heartbeat stomp, allora la connessione non viene chiusa ma rimane aperta 30 min.

Il ping che sono riuscito ad implementare fa accadere la stessa cosa dell'heartbeat, cioè se setto il timeout a 20 secondi e poi mando il ping a meno di 20 secondi la connessione rimane aperta per altri 20 secondi.

Ho anche provato ad aprire una connessione, mandare un messaggio di ping dopo 10 minuti, poi ho aspettato e la connessione si è chiusa lo stesso dopo 30 min (in totale dall'apertura).

Un altro problema è che non sono riuscito a individuare la ricezione del messaggio di ping, perché non riesco a capire dove viene mandato. Il messaggio viene senza dubbio mandato e ricevuto da qualche parte, altrimenti non prolungherebbe la connessione alla quale è stata settato un maxSessionIdleTimeout minore dell'intervallo di heartbeat.
Questo non mi permette di testare l'implementazione.

Il ramo dove c'è l'implementazione è questo: [be/connection-close](https://github.com/Studiofarma/Infolab/tree/be/connection-close)

**Comment by McGyv246** [comment]
Implemento la riconnessione con la chiusura

**Comment by paolo-venturi** [comment]
https://stackoverflow.com/questions/22361917/automatic-reconnect-with-stomp-js-in-node-js-application
