### ISSUE TITLE
Api di caricamento delle conversazioni

### ISSUE THREAD

**Issue by lucapiccinelli** [Studiofarma/Infolab#8]
Come utente della chat, vorrei vedere un elenco delle chat room (conversazioni) per le quali ci sono messaggi recenti.

Se chiamata senza parametri, l'API dovrà contenere l'elenco di tutte le room nelle quali ho inviato un messaggio. L'API accetta anche come paramtro opzionale d'ingresso una data. Se passata, l'elenco dovrà contenere solo le room che nelle quali ho inviato messaggi non più vecchi della data indicata.

L'API è di tipo GET, e il parametro `data` deve essere passato come parametro di query string nel formato `yyyy-MM-dd`

Le conversazioni utente-utente sono anch'esse delle chat room.

L'elenco sarà tornato in forma di Json Array. Ogni elemento dell'array deve contenere le informazioni indicate nel commento di Paolo qui sotto.

Per le informazioni che non abbiamo ancora a disposizione, mettete dei dati finti (avatar e numero messaggi non letti). Quando poi le informazioni saranno disponibili, le completeremo. Ad esempio il numero di messaggi non letti dipende dal completamento della storia https://github.com/Studiofarma/Infolab/issues/50

Per intenderci, nel frontend l'elenco delle room è quello che in slack corrisponde allo screenshot che segue.
![Image](https://user-images.githubusercontent.com/4964865/218406192-b1574c7b-4d0a-4c5c-bad7-ff8f3706ae94.png)

Nel nostro caso avremo un'unica room "general" e tutte le room delle conversazioni che abbiamo avuto con i singoli utenti.

**Comment by paolo-venturi** [comment]
Aggiungere un parametro per scegliere quanti messaggi scaricare
